- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: get VPC facts
    ec2_vpc_net_facts:
      region: us-east-1
      filters:
        "tag:Name" : "TestVPC"
    register: vpcfacts

  - debug:
      var: vpcfacts
  
  - name: get vpc ID
    set_fact: 
      vpc_ids: "{{ vpcfacts.vpcs|map(attribute='id')|list }}"

  - name: create alb sec group
    ec2_group:
      name: TestALBSG
      region: us-east-1
      description: sg for application load balancer
      vpc_id: "{{ vpc_ids.0 }}"